# Generated by Django 5.0.4 on 2024-04-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
