# Generated by Django 5.0.4 on 2024-05-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_user_email_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('storage_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
